// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SchemaInput struct {
	ID         string    `json:"id"`
	Required   []*string `json:"required"`
	Properties string    `json:"properties"`
	SchemaID   string    `json:"schemaId"`
}

type SchemaInputInput struct {
	ID         string    `json:"id"`
	Required   []*string `json:"required"`
	Properties string    `json:"properties"`
}
