version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 4
    networks:
      - invest-sense-network

  lake-gateway:
    image: fabiocaffarello/lake-gateway:latest
    container_name: lake-gateway
    ports:
      - 8000:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
      # mongodb:
      #   condition: service_healthy
    networks:
      - invest-sense-network

  # minio:
  #   image: bitnami/minio
  #   container_name: minio
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     MINIO_ACCESS_KEY: minio-access-key
  #     MINIO_SECRET_KEY: minio-secret-key
  #     MINIO_ROOT_USER: new-minio-root-user
  #     MINIO_ROOT_PASSWORD: new-minio-root-password
  #   volumes:
  #     - minio_data:/data
  #   networks:
  #     - invest-sense

  # ingestors-file-downloader:
  #   image: ingestors-file-downloader:latest
  #   container_name: ingestors-file-downloader
  #   env_file:
  #     - .env
  #   # depends_on:
  #   #   - rabbitmq
  #   networks:
  #     - invest-sense

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - invest-sense-network

networks:
  invest-sense-network:
    name: invest-sense-network
    driver: bridge

# volumes:
#   minio_data:
