// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Input struct {
	ID       string    `json:"id"`
	Data     string    `json:"data"`
	Metadata *Metadata `json:"metadata"`
	Status   *Status   `json:"status"`
}

type InputInput struct {
	Data string `json:"data"`
}

type Metadata struct {
	ProcessingID        string `json:"processingId"`
	ProcessingTimestamp string `json:"processingTimestamp"`
	Source              string `json:"source"`
	Service             string `json:"service"`
}

type Status struct {
	Code   int    `json:"code"`
	Detail string `json:"detail"`
}
