apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  # password123
  mongo-root-password: cGFzc3dvcmQxMjMK
  # replica1key
  mongo-password: c2VjcmV0cGFzc3dvcmQxMjMK
  mongo-replica-set-key: cmVwbGljYTFrZXkK

