package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	model1 "apps/lake-orchestration/lake-controller/internal/infra/graph/model"
	"context"
	"fmt"
)

// CreateConfig is the resolver for the createConfig field.
func (r *mutationResolver) CreateConfig(ctx context.Context, input model1.ConfigInput, source string, service string) (*model1.Config, error) {
	panic(fmt.Errorf("not implemented: CreateConfig - createConfig"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
