package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"apps/lake-manager/internal/infra/graph/model"
	"context"
	"fmt"
)

// CreateSchema is the resolver for the createSchema field.
func (r *mutationResolver) CreateSchema(ctx context.Context, input model.SchemaInputInput) (*model.SchemaInput, error) {
	panic(fmt.Errorf("not implemented: CreateSchema - createSchema"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
