FROM golang:latest as builder
WORKDIR /app
COPY . .
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN swag init -g cmd/server/main.go
RUN GOOS=linux CGO_ENABLED=1 go build -ldflags="-w -s" -o server ./cmd/server/main.go

# FROM scratch
# WORKDIR /app
# COPY --from=builder /app/server .
# COPY --from=builder /app/.env .env
# CMD ["tail", "-f", "/dev/null"]
CMD ["./server"]
