
POST http://localhost:8001/service/file-downloader/source/cnep HTTP/1.1
Content-Type: application/json

{
  "data": {
    "reference": {
      "year": 2023,
      "month": 8,
      "day": 28
    }
  }
}

###

GET http://localhost:8001/service/file-downloader HTTP/1.1
