POST http://localhost:8002/configs HTTP/1.1
Content-Type: application/json

{
  "name": "cnep-config",
  "active": true,
  "frequency": "daily",
  "service": "file-unzipper",
  "source": "cnep",
  "context": "br",
  "service_parameters": {
  },
  "job_parameters": {
  },
  "depends_on": [
    {"service": "file-downloader", "source": "cnep"}
  ]
}

###

GET http://localhost:8002/configs HTTP/1.1

###

GET http://localhost:8002/configs/file-downloader-cnep HTTP/1.1

###

GET http://localhost:8002/configs/service/file-downloader HTTP/1.1

###

