// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apps/lake-orchestration/lake-controller/internal/entity"
	"apps/lake-orchestration/lake-controller/internal/event"
	"apps/lake-orchestration/lake-controller/internal/infra/database"
	"apps/lake-orchestration/lake-controller/internal/infra/web/handlers"
	"apps/lake-orchestration/lake-controller/internal/usecase"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
	"libs/golang/events"
)

// Injectors from wire.go:

// [Use Case]
func NewCreateConfigUseCase(client *mongo.Client, eventDispatcher events.EventDispatcherInterface, database2 string) *usecase.CreateConfigUseCase {
	configRepository := database.NewConfigRepository(client, database2)
	configCreated := event.NewConfigCreated()
	createConfigUseCase := usecase.NewCreateConfigUseCase(configRepository, configCreated, eventDispatcher)
	return createConfigUseCase
}

// [Web Handler]
func NewWebConfigHandler(client *mongo.Client, eventDispatcher events.EventDispatcherInterface, database2 string) *handlers.WebConfigHandler {
	configRepository := database.NewConfigRepository(client, database2)
	configCreated := event.NewConfigCreated()
	webConfigHandler := handlers.NewWebConfigHandler(eventDispatcher, configRepository, configCreated)
	return webConfigHandler
}

func NewHealthzHandler() *handlers.WebHealthzHandler {
	webHealthzHandler := handlers.NewWebHealthzHandler()
	return webHealthzHandler
}

// wire.go:

var setConfigRepositoryDependency = wire.NewSet(database.NewConfigRepository, wire.Bind(
	new(entity.ConfigInterface),
	new(*database.ConfigRepository),
),
)

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewConfigCreated, wire.Bind(new(events.EventInterface), new(*event.ConfigCreated)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setConfigCreatedEvent = wire.NewSet(event.NewConfigCreated, wire.Bind(new(events.EventInterface), new(*event.ConfigCreated)))
