apiVersion: apps/v1
kind: Deployment
metadata:
  name: lake-manager
  labels:
    app: lake-manager
spec:
  selector:
    matchLabels:
      app: lake-manager
  replicas: 2
  template:
    metadata:
      name: lake-manager
      labels:
        app: lake-manager
    spec:
      serviceAccount: server
      containers:
        - name: lake-manager
          image: "fabiocaffarello/apis-lake-manager:latest"

          resources:
            requests:
              memory: 20Mi
              cpu: "0.03"
            limits:
              memory: 25Mi
              cpu: "0.03"

          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 10
            initialDelaySeconds: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1

          envFrom:
            - configMapRef:
                name: lake-manager-env
            - secretRef:
                name: lake-manager-secret


# ---


# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: lake-manager-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     name: lake-manager
#     kind: Deployment
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 25


# ---


# apiVersion: v1
# kind: Service
# metadata:
#   name: lake-manager
# spec:
#   selector:
#     app: lake-manager
#   type: LoadBalancer
#   ports:
#   - name: lake-manager
#     port: 8000
#     targetPort: 8000
#     protocol: TCP


# ---


# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: lake-manager-env
# data:
#   DB_DRIVER: "mysql"
#   DATABASE_HOST: "127.0.0.1"
#   DATABASE_PORT: "27017"
#   DATABASE_NAME: "mydb"
#   WEB_SERVER_PORT: "8000"
#   JWT_SECRET_KEY: "secret"
#   JWT_EXPIRES_IN: "300"


# ---


# apiVersion: v1
# kind: Secret
# metadata:
#   name: lake-manager-secret
# type: Opaque
# data:
#   DATABASE_USER: "dXNlcgo="
#   DATABASE_PASS: "cGFzc3dvcmQK"
