apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lake-manager-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: lake-manager
    kind: Deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
