apiVersion: v1
kind: Service
metadata:
  name: lake-manager
spec:
  selector:
    app: lake-manager
  type: LoadBalancer
  ports:
  - name: lake-manager
    port: 8000
    targetPort: 8000
    protocol: TCP
