POST http://localhost:8003/schemas HTTP/1.1
Content-Type: application/json

{
  "schema_type": "input-file-downloader-stocks",
  "service": "file-downloader",
  "source": "stocks",
  "json_schema": {
    "type": "object",
    "properties": {
      "url": {
        "type": "string"
      },
      "file": {
        "type": "string"
      },
      "reference": {
        "type": "string"
      }
    },
    "required": [
      "url",
      "file"
    ]
  }
}

###
GET http://localhost:8003/schemas HTTP/1.1
