// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Schema struct {
	ID         string `json:"id"`
	SchemaType string `json:"schemaType"`
	Service    string `json:"service"`
	Source     string `json:"source"`
	JSONSchema string `json:"JsonSchema"`
	SchemaID   string `json:"schemaId"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type SchemaInput struct {
	SchemaType string `json:"schemaType"`
	Service    string `json:"service"`
	Source     string `json:"source"`
	JSONSchema string `json:"JsonSchema"`
}
